name: Update Header Dependencies
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 10 1/16 * *'
jobs:
  updateHeader:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Latest CLI11 Tagged Release
        id: cli11-header
        run: |
          # Ping version information upstream
          CLI11_RELEASE_JSON=$(curl -sL https://api.github.com/repos/CLIUtils/CLI11/releases/latest)
          CLI11_RELEASE_VERSION=$(jq -r ".tag_name" <<< "$CLI11_RELEASE_JSON" | tr -d v)
          echo ::set-output name=release_tag::$(echo $CLI11_RELEASE_VERSION)
          # Extract out version information from git repository
          CLI11_VERSION_VALUE=$(grep -i ".*#define CLI11_VERSION \".*" src/mlpack/bindings/cli/third_party/CLI/CLI11.hpp | grep -Po '\d.\d.\d')
          # Set the current release tag
          echo ::set-output name=current_tag::$(echo $CLI11_VERSION_VALUE)

      - name: Get Latest Catch Tagged Release
        id: catch-header
        run: |
          # Ping version information upstream
          CATCH_RELEASE_JSON=$(curl -sL https://api.github.com/repos/catchorg/Catch2/releases/latest)
          CATCH_RELEASE_VERSION=$(jq -r ".tag_name" <<< "$CATCH_RELEASE_JSON" | tr -d v)
          echo ::set-output name=release_tag::$(echo $CATCH_RELEASE_VERSION)
          # Extract out version information from git repository
          CATCH_VERSION_MAJOR=$(grep -i ".*#define CATCH_VERSION_MAJOR.*" src/mlpack/tests/catch.hpp | grep -o "[0-9]*")
          CATCH_VERSION_MINOR=$(grep -i ".*#define CATCH_VERSION_MINOR.*" src/mlpack/tests/catch.hpp | grep -o "[0-9]*")
          CATCH_VERSION_PATCH=$(grep -i ".*#define CATCH_VERSION_PATCH.*" src/mlpack/tests/catch.hpp | grep -o "[0-9]*")
          # Combine values to match release tag information
          CATCH_VERSION_VALUE=${CATCH_VERSION_MAJOR}.${CATCH_VERSION_MINOR}.${CATCH_VERSION_PATCH}
          # Set the current release tag
          echo ::set-output name=current_tag::$(echo $CATCH_VERSION_VALUE)

      - name: Update CLI11
        if: steps.cli11-header.outputs.current_tag != steps.cli11-header.outputs.release_tag
        env:
          CURRENT_TAG: ${{ steps.cli11-header.outputs.current_tag }}
          RELEASE_TAG: ${{ steps.cli11-header.outputs.release_tag }}
        run: |
          # Delete the CLI11.hpp.
          rm -f src/mlpack/bindings/cli/third_party/CLI/CLI11.hpp
          # Download the release
          curl -sL https://github.com/CLIUtils/CLI11/releases/latest/download/CLI11.hpp -o src/mlpack/bindings/cli/third_party/CLI/CLI11.hpp

      - name: Update Catch
        if: steps.catch-header.outputs.current_tag != steps.catch-header.outputs.release_tag
        env:
          CURRENT_TAG: ${{ steps.catch-header.outputs.current_tag }}
          RELEASE_TAG: ${{ steps.catch-header.outputs.release_tag }}
        run: |
          # Delete the catch.hpp.
          rm -f src/mlpack/tests/catch.hpp
          # Download the release
          curl -sL https://github.com/catchorg/Catch2/releases/latest/download/catch.hpp -o src/mlpack/tests/catch.hpp

      - name: Create Pull Request For CLI11
        if: steps.cli11-header.outputs.current_tag != steps.cli11-header.outputs.release_tag
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Upgrade CLI11 to ${{ steps.cli11-header.outputs.release_tag }}
          title: Upgrade CLI11 to ${{ steps.cli11-header.outputs.release_tag }}
          body: |
            Updates [CLIUtils/CLI11][1] to ${{ steps.cli11-header.outputs.release_tag }}.
            Auto-generated by [create-pull-request][2]
            [1]: https://github.com/CLIUtils/CLI11
            [2]: https://github.com/peter-evans/create-pull-request
          labels: update headers deps, automated pr
          branch: cli11-header-updates-${{ steps.cli11-header.outputs.release_tag }}

      - name: Create Pull Request For Catch
        if: steps.catch-header.outputs.current_tag != steps.catch-header.outputs.release_tag
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Upgrade Catch to ${{ steps.catch-header.outputs.release_tag }}
          title: Upgrade Catch to ${{ steps.catch-header.outputs.release_tag }}
          body: |
            Updates [catchorg/Catch2][1] to ${{ steps.catch-header.outputs.release_tag }}.
            Auto-generated by [create-pull-request][2]
            [1]: https://github.com/catchorg/Catch2
            [2]: https://github.com/peter-evans/create-pull-request
          labels: update headers deps, automated pr
          branch: catch-header-updates-${{ steps.catch-header.outputs.release_tag }}
