name: Update CLI11
on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '0 10 1/16 * *'
jobs:
  updateCLI11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Get Latest CLI11 Tagged Release
        id: cli11-header
        run: |
          # Ping version information upstream
          CLI11_RELEASE_JSON=$(curl -sL https://api.github.com/repos/CLIUtils/CLI11/releases/latest)
          CLI11_RELEASE_VERSION=$(jq -r ".tag_name" <<< "$CLI11_RELEASE_JSON" | tr -d v)
          echo ::set-output name=release_tag::$(echo $CLI11_RELEASE_VERSION)
          # Extract out version information from git repository
          CLI11_VERSION_VALUE=$(grep -i ".*#define CLI11_VERSION \".*" src/mlpack/bindings/cli/third_party/CLI/CLI11.hpp | grep -Po '\d.\d.\d')
          # Set the current release tag
          echo ::set-output name=current_tag::$(echo $CLI11_VERSION_VALUE)

      - name: Update CLI11
        if: steps.cli11-header.outputs.current_tag != steps.cli11-header.outputs.release_tag
        env:
          CURRENT_TAG: ${{ steps.cli11-header.outputs.current_tag }}
          RELEASE_TAG: ${{ steps.cli11-header.outputs.release_tag }}
        run: |
          # Delete the CLI11.hpp.
          rm -f src/mlpack/bindings/cli/third_party/CLI/CLI11.hpp
          # Download the release
          curl -sL https://github.com/CLIUtils/CLI11/releases/latest/download/CLI11.hpp -o src/mlpack/bindings/cli/third_party/CLI/CLI11.hpp

      - name: Create Pull Request For CLI11
        if: steps.cli11-header.outputs.current_tag != steps.cli11-header.outputs.release_tag
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Upgrade CLI11 to ${{ steps.cli11-header.outputs.release_tag }}
          title: Upgrade CLI11 to ${{ steps.cli11-header.outputs.release_tag }}
          body: |
            Updates [CLIUtils/CLI11][1] to ${{ steps.cli11-header.outputs.release_tag }}.
            Auto-generated by [create-pull-request][2]
            [1]: https://github.com/CLIUtils/CLI11
            [2]: https://github.com/peter-evans/create-pull-request
          labels: update headers deps, automated pr
          branch: cli11-header-updates-${{ steps.cli11-header.outputs.release_tag }}
